using System.Reflection;
[assembly: AssemblyTitle("Schtrix")]
[assembly: AssemblyDescription("Universal barcode reader")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nikolai Voronin")]
[assembly: AssemblyProduct("Schtrix")]
[assembly: AssemblyCopyright("Copyright © 2015-2017 Nikolai Voronin")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.1.*")]
